let country_list = {
  "AED": { country: "United Arab Emirates", name: "Dirham", code: "AE" },
  "AFN": { country: "Afghanistan", name: "Afghani", code: "AF" },
  "ALL": { country: "Albania", name: "Lek", code: "AL" },
  "AMD": { country: "Armenia", name: "Dram", code: "AM" },
  "ANG": { country: "Netherlands Antilles", name: "Guilder", code: "NL" },
  "AOA": { country: "Angola", name: "Kwanza", code: "AO" },
  "ARS": { country: "Argentina", name: "Peso", code: "AR" },
  "AUD": { country: "Australia", name: "Dollar", code: "AU" },
  "AWG": { country: "Aruba", name: "Florin", code: "AW" },
  "AZN": { country: "Azerbaijan", name: "Manat", code: "AZ" },
  "BAM": { country: "Bosnia and Herzegovina", name: "Convertible Mark", code: "BA" },
  "BBD": { country: "Barbados", name: "Dollar", code: "BB" },
  "BDT": { country: "Bangladesh", name: "Taka", code: "BD" },
  "BGN": { country: "Bulgaria", name: "Lev", code: "BG" },
  "BHD": { country: "Bahrain", name: "Dinar", code: "BH" },
  "BIF": { country: "Burundi", name: "Franc", code: "BI" },
  "BMD": { country: "Bermuda", name: "Dollar", code: "BM" },
  "BND": { country: "Brunei", name: "Dollar", code: "BN" },
  "BOB": { country: "Bolivia", name: "Boliviano", code: "BO" },
  "BRL": { country: "Brazil", name: "Real", code: "BR" },
  "BSD": { country: "Bahamas", name: "Dollar", code: "BS" },
  "BTN": { country: "Bhutan", name: "Ngultrum", code: "BT" },
  "BWP": { country: "Botswana", name: "Pula", code: "BW" },
  "BYN": { country: "Belarus", name: "Ruble", code: "BY" },
  "BZD": { country: "Belize", name: "Dollar", code: "BZ" },
  "CAD": { country: "Canada", name: "Dollar", code: "CA" },
  "CHF": { country: "Switzerland", name: "Franc", code: "CH" },
  "CLP": { country: "Chile", name: "Peso", code: "CL" },
  "CNY": { country: "China", name: "Yuan", code: "CN" },
  "COP": { country: "Colombia", name: "Peso", code: "CO" },
  "CRC": { country: "Costa Rica", name: "Colon", code: "CR" },
  "CZK": { country: "Czech Republic", name: "Koruna", code: "CZ" },
  "DKK": { country: "Denmark", name: "Krone", code: "DK" },
  "DOP": { country: "Dominican Republic", name: "Peso", code: "DO" },
  "DZD": { country: "Algeria", name: "Dinar", code: "DZ" },
  "EGP": { country: "Egypt", name: "Pound", code: "EG" },
  "EUR": { country: "European Union", name: "Euro", code: "EU" },
  "FJD": { country: "Fiji", name: "Dollar", code: "FJ" },
  "GBP": { country: "United Kingdom", name: "Pound Sterling", code: "GB" },
  "GHS": { country: "Ghana", name: "Cedi", code: "GH" },
  "HKD": { country: "Hong Kong", name: "Dollar", code: "HK" },
  "HRK": { country: "Croatia", name: "Kuna", code: "HR" },
  "HUF": { country: "Hungary", name: "Forint", code: "HU" },
  "IDR": { country: "Indonesia", name: "Rupiah", code: "ID" },
  "ILS": { country: "Israel", name: "Shekel", code: "IL" },
  "INR": { country: "India", name: "Rupee", code: "IN" },
  "IQD": { country: "Iraq", name: "Dinar", code: "IQ" },
  "ISK": { country: "Iceland", name: "Krona", code: "IS" },
  "JPY": { country: "Japan", name: "Yen", code: "JP" },
  "KES": { country: "Kenya", name: "Shilling", code: "KE" },
  "KRW": { country: "South Korea", name: "Won", code: "KR" },
  "KWD": { country: "Kuwait", name: "Dinar", code: "KW" },
  "KZT": { country: "Kazakhstan", name: "Tenge", code: "KZ" },
  "LAK": { country: "Laos", name: "Kip", code: "LA" },
  "LBP": { country: "Lebanon", name: "Pound", code: "LB" },
  "LKR": { country: "Sri Lanka", name: "Rupee", code: "LK" },
  "LYD": { country: "Libya", name: "Dinar", code: "LY" },
  "MAD": { country: "Morocco", name: "Dirham", code: "MA" },
  "MDL": { country: "Moldova", name: "Leu", code: "MD" },
  "MMK": { country: "Myanmar", name: "Kyat", code: "MM" },
  "MNT": { country: "Mongolia", name: "Tugrik", code: "MN" },
  "MOP": { country: "Macau", name: "Pataca", code: "MO" },
  "MUR": { country: "Mauritius", name: "Rupee", code: "MU" },
  "MXN": { country: "Mexico", name: "Peso", code: "MX" },
  "MYR": { country: "Malaysia", name: "Ringgit", code: "MY" },
  "NGN": { country: "Nigeria", name: "Naira", code: "NG" },
  "NOK": { country: "Norway", name: "Krone", code: "NO" },
  "NPR": { country: "Nepal", name: "Rupee", code: "NP" },
  "NZD": { country: "New Zealand", name: "Dollar", code: "NZ" },
  "OMR": { country: "Oman", name: "Rial", code: "OM" },
  "PEN": { country: "Peru", name: "Sol", code: "PE" },
  "PHP": { country: "Philippines", name: "Peso", code: "PH" },
  "PKR": { country: "Pakistan", name: "Rupee", code: "PK" },
  "PLN": { country: "Poland", name: "Zloty", code: "PL" },
  "QAR": { country: "Qatar", name: "Riyal", code: "QA" },
  "RON": { country: "Romania", name: "Leu", code: "RO" },
  "RSD": { country: "Serbia", name: "Dinar", code: "RS" },
  "RUB": { country: "Russia", name: "Ruble", code: "RU" },
  "SAR": { country: "Saudi Arabia", name: "Riyal", code: "SA" },
  "SEK": { country: "Sweden", name: "Krona", code: "SE" },
  "SGD": { country: "Singapore", name: "Dollar", code: "SG" },
  "THB": { country: "Thailand", name: "Baht", code: "TH" },
  "TRY": { country: "Turkey", name: "Lira", code: "TR" },
  "TWD": { country: "Taiwan", name: "Dollar", code: "TW" },
  "UAH": { country: "Ukraine", name: "Hryvnia", code: "UA" },
  "USD": { country: "United States", name: "Dollar", code: "US" },
  "UYU": { country: "Uruguay", name: "Peso", code: "UY" },
  "UZS": { country: "Uzbekistan", name: "Som", code: "UZ" },
  "VND": { country: "Vietnam", name: "Dong", code: "VN" },
  "ZAR": { country: "South Africa", name: "Rand", code: "ZA" },
  "ZMW": { country: "Zambia", name: "Kwacha", code: "ZM" }
};
